### ISSUE TITLE
Unable to download old esp8266 sdk files for deauth

### ISSUE THREAD

**Issue by r3dpan** [markszabo/Hacktivity2016#3]
I'm currently working on a little side project where your code + explanation was very helpful so far. Now i'm trying to program a function that sends deauth frames from my esp8266. Like it is already explained in the readme of your project you need to setup an older sdk version to get this to work. I tryed following your instructions to do so. Sadly executing the get.py script to get the needed tools in the last steps always fails because of a hash mismatch. Directly downloading the needed files (got paths from the package_esp8266com_index.template.json) from http://arduino.esp8266.com/linux64-xtensa-lx106-elf-gb404fb9.tar.gz doesn't work either because they don't seem to exist anymore. Is there still another way to setup the older sdk or to retrieve those files?

**Comment by markszabo** [comment]
Well, I haven't been working with this for a while now. Have you tried setting it up with the latest sdk, and once it compiles fine, then replacing the sdk with the old one? (And hoping that the tools did not change too much since then.)

Alternatively you can try to disable hash checking by editing the python file. If you provide the error message you are getting, I can help with that.

**Comment by r3dpan** [comment]
Thank you very much for your answer.
I did try the workaround you suggested above but that did not exactly work out for me.
I did find a solution for the problem on my own tho.

Like i already explained in my first post you can find the source url's of the needed tools in the package_esp8266com_index.template.json file (inside package folder of downloaded SDK).
It looks like the links for the xtensa-lx106-elf-gcc package are outdated and now obsolete.
Through google i found another github repository with a similar project to this. This project obviously needed the same old SDK to compile it's code and therefore needed the same packages that i was unable to download with the original script provided. So naturally another user ran into the same issue that i had. Luckily the project owner already provided a list with new url's for this specific package.

To fix this issue one simply needs to open package_esp8266com_index.template.json in a text editor and change the url of the xtensa-lx106-elf-gcc package for the specific platform.

New Url's:
- i686-mingw32
https://github.com/esp8266/Arduino/releases/download/2.3.0/win32-xtensa-lx106-elf-gb404fb9-2.tar.gz

- x86_64-apple-darwin
https://github.com/esp8266/Arduino/releases/download/2.3.0/osx-xtensa-lx106-elf-gb404fb9-2.tar.gz

- i386-apple-darwin
https://github.com/esp8266/Arduino/releases/download/2.3.0/osx-xtensa-lx106-elf-gb404fb9-2.tar.gz

- x86_64-pc-linux-gnu
https://github.com/esp8266/Arduino/releases/download/2.3.0/linux64-xtensa-lx106-elf-gb404fb9.tgz

- i686-pc-linux-gnu
https://github.com/esp8266/Arduino/releases/download/2.3.0/linux32-xtensa-lx106-elf.tar.gz

Source thread: https://github.com/spacehuhn/esp8266_deauther/issues/1109

**Comment by markszabo** [comment]
Great, I'm glad you could solve it and thank you for sharing the solution.
